[package]
name = "my_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.27", features = ["derive"] }
lazy_static = "1.5.0"
memmap2 = "0.9.5"
rayon = "1.10.0"
regex = "1.11.1"
rustyline = "15.0.0"
zip = "2.2.2"
